version: 1.0.{build}
skip_non_tags: true
skip_branch_with_pr: true
image:
- macOS-Sonoma
- Visual Studio 2022
- Ubuntu2204
clone_depth: 1
build:
  verbosity: minimal
test: off
stack: python 3.11

install:
- pip install -r requirements.txt
- pip install PyInstaller

build_script:
- flet pack main.py --name aiprompt --product-name aiprompt

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2022

  after_build:
  - 7z a aiprompt-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: aiprompt-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS-Sonoma

  after_build:
  - tar -czvf aiprompt-macos.tar.gz -C dist aiprompt.app

  artifacts:
  - path: aiprompt-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu2204

  after_build:
  - tar -czvf aiprompt-linux.tar.gz -C dist aiprompt

  artifacts:
  - path: aiprompt-linux.tar.gz
